= Pflichtenheft MusicQuiz
// Metadata
:author: Benjamin Besic, David Ignjatovic, Bozidar Spasenovic
:email:
:date: yyyy-mm-dd
:revision:  1.0
// Settings
:source-highlighter: coderay
:icons: font
//:sectnums:    // Nummerierung der Überschriften / section numbering
// Refs:
:imagesdir: images
:sourcedir-code: src/main/java/at/htl/jdbcprimer
:sourcedir-test: src/test/java/at/htl/jdbcprimer
:toc:

Version: {revision}

++++
<link rel="stylesheet"  href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
++++

== Motivation
Projekt wird im Rahmen des Gegenstandes „Projektentwicklung“ durchgeführt

== Ausgangssituation
Viele Leute hören sich täglich viele Songs an und wissen meist nichtmal wie sie heißen bzw.
wer sie gemacht hat.

=== Ist-Zustand
Es gibt viele denen langweilig ist und die gleichzeitig auch ein großes Wissen über Musik besitzen.

== Zielsetzung
Das Ziel ist es eine Webapp zu machen, in der man Songs anhand von Hörproben erraten kann (Interpret, Name)
und eine dazugehöriges Punktesystem und in der Zukunft kann man auch gegen andere Benutzer
spielen.

[plantuml]
....
@startuml
Left to right direction
Class Spiel
Class Spieler
Class Song
Class Punkte
Class Gegner
Spieler -- Punkte
Spiel -- Spieler
Spiel -- Song
Gegner -> Spieler
Gegner -- Spiel
@enduml
....

image::http://www.plantuml.com/plantuml/png/SoWkIImgAStDuV99JIjHACbNACfCpoXHICaiIaqkoSpFutBEIImkLWWko4pDKK3cf1R1UFbvwL1cG6bUTaagbEEUcfu7L0HLhA2h2vM6Y83uK2cu0CGea3wGUZkOF5G4heFB8JKl1UXa0000[Example]

=== Funktionale Anforderungen
[plantuml]
....
@startuml
left to right direction
:Spieler:
rectangle Spiel{
Spieler -- (Eingabe des eigenen Namen)
Spieler -- (Eingabe des Songnamen)
Spieler -- (Eingabe des Künstlernamen)
Spieler -- (Anzahl der Punkte sehen)
}
(Eingabe des eigenen Namen) -- Spielerdatenbank
(Eingabe des Songnamen) -- Songdatenbank
(Eingabe des Künstlernamen) -- Songdatenbank
(Anzahl der Punkte sehen) -- Spielerdatenbank
@enduml
....
image::http://www.plantuml.com/plantuml/png/VOunhi8m44HxdsBB_ujS85Keg90GKawmmODZnTaWUzE0k1aT5oD6APsKC_DszPga77KUWmcuAUb4qRjUoVg8g_f9JDtUFG9YRNB3uWBeLptDkb1LqT_HY-CEP948ta4WTEOHyh-9jPCusKTEdxSaNPO2Tv07zu7i4Y-p30fAw3FqCZis-NJzObaX7SjWDhGocrC1BCWLw2t5eaG3iVCOlW00[Example]
=== Nichtfunktionale Anforderungen
* Usability, das GUI muss einfach zu benutzen sein
* Reliability, Songs müssen abgespielt werden, alle Daten müssen immer eingetragen werden
* Efficiency, es soll alles so effizient wie möglich gespeichert und abgerufen werden

== Mengengerüst
Es werden meiste mehrere Nutzer gleichzeitig spielen, die in der Datenbank mit ihren Punkten gespeichert werden. +
Anfangs werden 30 Songs und deren Infos in die Datenbank gespeichert, auf Bedarf wird die Anzahl vergrößert.






